# Generated by Django 4.2.4 on 2023-08-12 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Albums",
            fields=[
                (
                    "albumid",
                    models.AutoField(
                        db_column="AlbumId", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.TextField(db_column="Title")),
            ],
            options={
                "db_table": "albums",
            },
        ),
        migrations.CreateModel(
            name="Artists",
            fields=[
                (
                    "artistid",
                    models.AutoField(
                        db_column="ArtistId", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField(blank=True, db_column="Name", null=True)),
            ],
            options={
                "db_table": "artists",
            },
        ),
        migrations.CreateModel(
            name="Genres",
            fields=[
                (
                    "genreid",
                    models.AutoField(
                        db_column="GenreId", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField(blank=True, db_column="Name", null=True)),
            ],
            options={
                "db_table": "genres",
            },
        ),
        migrations.CreateModel(
            name="MediaTypes",
            fields=[
                (
                    "mediatypeid",
                    models.AutoField(
                        db_column="MediaTypeId", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField(blank=True, db_column="Name", null=True)),
            ],
            options={
                "db_table": "media_types",
            },
        ),
        migrations.CreateModel(
            name="Tracks",
            fields=[
                (
                    "trackid",
                    models.AutoField(
                        db_column="TrackId", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField(db_column="Name")),
                (
                    "composer",
                    models.TextField(blank=True, db_column="Composer", null=True),
                ),
                ("milliseconds", models.IntegerField(db_column="Milliseconds")),
                (
                    "bytes",
                    models.IntegerField(blank=True, db_column="Bytes", null=True),
                ),
                ("unitprice", models.TextField(db_column="UnitPrice")),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        db_column="AlbumId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="music.albums",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        blank=True,
                        db_column="GenreId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="music.genres",
                    ),
                ),
                (
                    "mediatype",
                    models.ForeignKey(
                        db_column="MediaTypeId",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="music.mediatypes",
                    ),
                ),
            ],
            options={
                "db_table": "tracks",
            },
        ),
        migrations.AddField(
            model_name="albums",
            name="artist",
            field=models.ForeignKey(
                db_column="ArtistId",
                on_delete=django.db.models.deletion.CASCADE,
                to="music.artists",
            ),
        ),
    ]
