# Generated by Django 4.2.4 on 2023-08-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0002_artistimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracks",
            name="albumid",
            field=models.ForeignKey(
                blank=True,
                db_column="AlbumId",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tracks",
                to="music.albums",
            ),
        ),
    ]
